### ISSUE TITLE
Kubernetes pod communication issue

### ISSUE THREAD

**Issue by DeborggraeveR** [projectcalico/cni-plugin#792] opened 2019-09-24 07:12 UTC
In the past i have been running kubernetes with calico cni without any issues. Our dev environment is kubernetes 1.15.2 with calico v3.3.6 and run without issues.
For several weeks now im trying to get our production environment up and running using a new version of kubernetes and calico. I have tried with kubernetes 1.15/calico 3.8 and last few days kubernetes 1.16/calico 3.9.
After reinstalling the servers and full cluster several times with different configurations, last night i made a clean install again, with the same issue. After removing calico again and try weave cni plugin everything works fine, so this seems to be an issue with calico.
The issue occurs with both CRIO and Docker as container engine, both in single master and HA setups.

## Expected Behavior
Curl requests to a pod should succeed from any node in the cluster.

## Current Behavior
When running kubernetes with calico plugin, communication with pods on other nodes fail.
When i send a curl request to a pod running on the node connected to, the request is successful.
When i send a curl request to a pod running on another node, the request fail.
Example:
Curl request to pod A running on node A while connected to node A = OK
Curl request to pod B running on node B while connected to node B = OK
Curl request to pod A running on node A while connected to node B = FAIL
Curl request to pod B running on node B while connected to node A = FAIL

## Steps to Reproduce (for bugs)
1. Install CRIO
2. Install Kubernetes
3. Apply https://docs.projectcalico.org/v3.9/manifests/calico.yaml
4. Send curl request to a pod running on a different node

## Context
Apply the kubernetes dashboard and send curl request to the dashboard. Some requests succeed, some fail. Send a request to one of the .js files that is used by the dashboard.
Same issue with the traefik dashboard
Running a private docker registery, when trying to push an image, it start uploading a small part of the image, then stops.

## Your Environment
* CNI plugin version (e.g. `/opt/cni/bin/calico --version`): v3.9.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.16.0
* Operating System and version: Ubuntu 18.04

**Comment by DeborggraeveR** [comment] 2019-09-24 08:41
After switching back from weave to calico and search the internet bit more, i finally found a solution to the problem. As i notice more people run into this issue, it might be usefull to mention this information clearly in the documentation.

Found the solution using the URL: https://developer.ibm.com/recipes/tutorials/troubleshooting-network-issues-for-ibm-cloud-private-icp-on-openstack/
See Step 7:

Tunnel interfaces should be 20 bytes less than the network MTU for your network. This is due to the extra 20-byte header that the tunnel will add to each packet. Without this 20-byte difference in the MTUs, some large file transfer might not work in the environment. For more details see, https://github.com/projectcalico/calico/blob/master/v2.4/usage/configuration/mtu.md#selecting-mtu-size

As my server provider VLAN has a MTU of 1450, i had to reduce the calico MTU to 1430. After restarting all nodes, all network traffic seems to run fine.

ens10: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 10.0.0.2  netmask 255.255.255.255  broadcast 10.0.0.2
        inet6 fe80::8400:ff:fe31:2f81  prefixlen 64  scopeid 0x20<link>
        ether 86:00:00:31:2f:81  txqueuelen 1000  (Ethernet)
        RX packets 13668  bytes 7387756 (7.3 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 11733  bytes 3518333 (3.5 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

tunl0: flags=193<UP,RUNNING,NOARP>  mtu 1430
        inet 10.244.57.0  netmask 255.255.255.255
        tunnel   txqueuelen 1000  (IPIP Tunnel)
        RX packets 298  bytes 2335456 (2.3 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 187  bytes 10738 (10.7 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by tmjd** [comment] 2019-09-24 13:12
Thank you for reporting the solution you found.
I am surprised that switching to a newer version of Calico caused this, I don't believe there have been any changes in MTU handling in Calico for a very long time.

**Comment by waheedi** [comment] 2020-10-06 15:05
Well I had a similar issue, and the reason was FORWARD traffic was dropped by default:

master-node: `iptables -S FORWARD`

```
-P FORWARD DROP
-A FORWARD -m comment --comment "cali:wUHhoiAYhphO9Mso" -j cali-FORWARD
-A FORWARD -m comment --comment "kubernetes forwarding rules" -j KUBE-FORWARD
-A FORWARD -m conntrack --ctstate NEW -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A FORWARD -j DOCKER-USER
-A FORWARD -j DOCKER-ISOLATION-STAGE-1
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
```

**Comment by ratulb** [comment] 2020-10-19 00:53
Facing similar issue - not able communicate across PODs as well as to internet.

root@master:~# iptables -S FORWARD
-P FORWARD ACCEPT
-A FORWARD -m comment --comment "cali:wUHhoiAYhphO9Mso" -j cali-FORWARD
-A FORWARD -m comment --comment "kubernetes forwarding rules" -j KUBE-FORWARD
-A FORWARD -m conntrack --ctstate NEW -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A FORWARD -m comment --comment "cali:S93hcgKJrXEqnTfs" -m comment --comment "Policy explicitly accepted packet." -m mark --mark 
0x10000/0x10000 -j ACCEPT




root@master:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", G
itTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", G
itTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

**Comment by ratulb** [comment] 2020-10-19 01:31
Also,
In my case MTU seems alright - still not able communicate PODs deployed across nodes!

root@master:~# **/opt/cni/bin/calico -v
v3.16.3**
root@master:~# ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: **ens4**: <BROADCAST,MULTICAST,UP,LOWER_UP> **mtu 1460** qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 42:01:0a:94:00:0c brd ff:ff:ff:ff:ff:ff
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default 
    link/ether 02:42:1b:e2:0b:b4 brd ff:ff:ff:ff:ff:ff
4: **tunl0@NONE:** <NOARP,UP,LOWER_UP> **mtu 1440** qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
7: cali9d09eaa3519@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1440 qdisc noqueue state UP mode DEFAULT group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 0
8: **cali3319d29c0ca@if4**: <BROADCAST,MULTICAST,UP,LOWER_UP> **mtu 1440** qdisc noqueue state UP mode DEFAULT group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 1

**Comment by caseydavenport** [comment] 2020-11-19 22:24
@ratulb I'd recommend opening another issue if this is still affecting you, since it sounds like it might be a different root cause.

Since the original issue was resolved I'm going to close this. Also worth noting that Calico v3.17 will include automatic MTU detection, which should hopefully make scenarios like this less likely.

**Closed by caseydavenport** 2020-11-19 22:24 UTC
Labels: kind/support
