### ISSUE TITLE
Configurable option to log to stdout/stderr and also to a file

### ISSUE THREAD

**Issue by leodotcloud** [projectcalico/cni-plugin#274] opened 2017-02-17 00:24 UTC
Looking at https://github.com/projectcalico/cni-plugin/blob/master/utils/utils.go#L222, the logging is redirected to stderr. So when the CNI plugin is invoked, all the logs show up in the context of orchestration engine.

It would be nice if the CNI config has a configurable option to log to a file as well? That way the log of the CNI plugins can be seen using `docker logs cnicontainerid`.

This is what we do at Rancher and it has been very useful for us while debugging.
Config option:
- https://github.com/rancher/rancher-cni-bridge/blob/v0.1.3/config.go#L24
- https://github.com/rancher/rancher-cni-ipam/blob/v0.1.1/config.go#L14

Log to file: 
- https://github.com/rancher/rancher-cni-bridge/blob/v0.1.3/bridge.go#L55
- https://github.com/rancher/rancher-cni-ipam/blob/v0.1.1/main.go#L30

**Comment by tomdee** [comment] 2017-02-17 01:51
See also #126

**Comment by caseydavenport** [comment] 2017-08-03 21:44
I'm going to close this as a duplicate of #126.

**Closed by caseydavenport** 2017-08-03 21:44 UTC
Labels: kind/enhancement
