### ISSUE TITLE
Inefficient lists degrade Kubernetes scalability

### ISSUE THREAD

**Issue by jkaniuk** [projectcalico/cni-plugin#838] opened 2020-02-17 12:18 UTC
Calico integration with Kubernetes issues problematic calls that are quite heavy for kube-apiserver on large clusters:
- 1840 calls (5 > 1s, 155 > 100ms),  verb="GET" URI="/api/v1/nodes" UserAgent="calico-typha/v0.0.0
- 5 calls (1 > 1s) verb="GET" URI="/api/v1/pods" UserAgent="calico-typha/v0.0.0
- 178 calls (9 > 100ms) verb="GET" URI="/api/v1/nodes" UserAgent="cpvpa/v0.0.0

Those calls should be translated to watches, as watch behavior is much more efficient:
- it first call /api/v1/pods?resourceVersion=0 (which causes kube-apiserver to serve it from cache instead of fetching newest version from etcd)
- then periodic starts watches on changes since last fetched resourceVersion

Periodic 100 nodes scalability tests with Calico enabled are failing (mostly red):
https://k8s-testgrid.appspot.com/sig-scalability-experiments#calico
one of failed 100 node scalability runs:  
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-networkpolicies/1223218919838322690
```
testing/density/config.yaml
measurement call WaitForControlledPodsRunning - WaitForRunningLatencyDeployments error: 112 objects timed out:
Deployments: test-hw0cik-1/latency-deployment-448, test-hw0cik-1/latency-deployment-446, ...
measurement call PodStartupLatency - PodStartupLatency error: pod startup: too high latency 90th percentile: got 15m35.292351924s expected: 5s]
```

Calico calls to kube-apiserver could be found here:  
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-networkpolicies/1223218919838322690/artifacts/e2e-scalability-calico-master/kube-apiserver.log

**Comment by caseydavenport** [comment] 2020-02-20 22:50
@jkaniuk thanks for reporting this. We'll look in to what's going on here, but to my knowledge we shouldn't be performing GET calls - the design is to use WATCH based on latest resourceVersion. So, this might be a bug rather than "working as intended".

**Comment by caseydavenport** [comment] 2020-02-20 22:51
@jkaniuk what version of Calico are you using for these tests?

**Comment by caseydavenport** [comment] 2020-03-11 11:29
I think you are probably encountering the bug that was fixed by this PR in Calico v3.13.0: https://github.com/projectcalico/libcalico-go/pull/1192

**Comment by spikecurtis** [comment] 2020-03-17 22:59
@caseydavenport I don't expect GETs on nodes to have been affected by the fix you pointed to. That only affected watches on network policies.

**Comment by caseydavenport** [comment] 2020-03-19 23:47
@spikecurtis wasn't the result of that bug that we would perform unnecessary GET requests each time we lost our watch / resync'd?

**Comment by caseydavenport** [comment] 2020-03-20 00:00
Nevermind you're right, I missed that.

**Comment by caseydavenport** [comment] 2020-05-15 16:04
I believe this has been fixed in master now and will show up in Calico v3.15.0.

There were two root causes:
- https://github.com/projectcalico/libcalico-go/pull/1231
- https://github.com/projectcalico/typha/pull/366

Thanks much for reporting this!

**Closed by caseydavenport** 2020-05-15 16:04 UTC
Labels: impact/high, kind/bug, likelihood/low
