### ISSUE TITLE
BUG：install-cni.sh in docker container

### ISSUE THREAD

**Issue by aesirteam** [projectcalico/cni-plugin#844] opened 2020-02-27 05:47 UTC
## Steps to Reproduce (for bugs)

docker logs xxxxx

Installing any TLS assets from /calico-secrets
Wrote Calico CNI binaries to /host/opt/cni/bin
CNI plugin version: v3.12.0
/host/secondary-bin-dir is non-writeable, skipping
Using CNI config template from CNI_NETWORK_CONFIG environment variable.
/install-cni.sh: line 169: hostname: command not found
CNI config: {
  "name": "k8s-pod-network",
  "cniVersion": "0.3.1",
  "plugins": [
    {
      "type": "calico",
      "log_level": "info",
      "etcd_endpoints": "https://10.204.80.6:2379,https://10.204.80.7:2379,https://10.204.80.8:2379",
      "etcd_key_file": "/etc/cni/net.d/calico-tls/etcd-key",
      "etcd_cert_file": "/etc/cni/net.d/calico-tls/etcd-cert",
      "etcd_ca_cert_file": "/etc/cni/net.d/calico-tls/etcd-ca",
      "mtu": 1440,
      "ipam": {"type": "calico-ipam"},
      "policy": {"type": "k8s"},
      "kubernetes": {"kubeconfig": "/etc/cni/net.d/calico-kubeconfig"}
    },{
      "type": "portmap",
      "snat": true,
      "capabilities": {"portMappings": true}
    }
  ]
}
/install-cni.sh: line 195: [-z: command not found
Created CNI config 10-calico.conflist
Done configuring CNI.  Sleep=false

## Your Environment

* CNI plugin version : v3.12.0
* Orchestrator version : kubernetes
* CNI config:
{
  "name": "k8s-pod-network",
  "cniVersion": "0.3.1",
  "plugins": [
    {
      "type": "calico",
      "log_level": "info",
      "etcd_endpoints": "https://10.204.80.6:2379,https://10.204.80.7:2379,https://10.204.80.8:2379",
      "etcd_key_file": "/etc/cni/net.d/calico-tls/etcd-key",
      "etcd_cert_file": "/etc/cni/net.d/calico-tls/etcd-cert",
      "etcd_ca_cert_file": "/etc/cni/net.d/calico-tls/etcd-ca",
      "mtu": 1440,
      "ipam": {"type": "calico-ipam"},
      "policy": {"type": "k8s"},
      "kubernetes": {"kubeconfig": "/etc/cni/net.d/calico-kubeconfig"}
    },{
      "type": "portmap",
      "snat": true,
      "capabilities": {"portMappings": true}
    }
  ]
}
* Operating System and version: CentOS 7.5
* Link to your project (optional):

**Comment by caseydavenport** [comment] 2020-02-27 19:39
I think this is a duplicate of https://github.com/projectcalico/cni-plugin/issues/835

We're working on the fix for the error.

**Closed by caseydavenport** 2020-02-27 19:39 UTC

**Comment by aesirteam** [comment] 2020-02-28 05:28
but:
/install-cni.sh: line 169: hostname: command not found
