### ISSUE TITLE
Support calico-ipam for multus interface with more functionality

### ISSUE THREAD

**Issue by vivekskrishna** [projectcalico/cni-plugin#1193] opened 2021-10-14 18:07 UTC
Looking for way to extend the functionality of calico-ipam so that we can support other attributes like routes etc similar to whereabouts so that calico-ipam can be used as ipam for secondary interfaces when using multus.

Right now the only cluster wide ipam which can be used for secondary interfaces are whereabouts or dhcp. This change request is trying to leverage calico-ipam for the same functionality.

## Current Behavior
Currently calico-ipam supports only ipools which can be used to allocate ip from specific ranges. since we are talking about secondary interfaces when using multus, pods network namespace would ideally also need ability to route packets to different gateways for certain subnets. so having ability to add routes inside a pod is needed at minimum to use calico-ipam with multus

## Possible Solution
add the arguements which are supported by solutions like host-local, whereabouts etc which will provide improved functionality.

## Context
As of now we are not able to use calico-ipam as the ipam for multus interfaces. having a single ipam plaugin for all networking needs would simplify the k8s cluster operationally.

## Your Environment
Primarily k8s+calico(primary cni) + multus and its plugins

**Comment by caseydavenport** [comment] 2021-10-29 21:45
Sorry for the delay, I believe this is a duplicate of another issue, so going to close this to keep discussion in one place on this issue: https://github.com/projectcalico/cni-plugin/issues/429

**Closed by caseydavenport** 2021-10-29 21:45 UTC
