### ISSUE TITLE
Not able to add calico as second interface

### ISSUE THREAD

**Issue by pawansingh126** [projectcalico/cni-plugin#678] opened 2019-01-28 17:23 UTC
Not able to add calico CNI as second network interface to a pod. Works fine as primary.
## Expected Behavior
Should be able to add calico as second interface on a pod.

works: calico (primary:p) + weave (secondary:s) 
works: calico (p)

Should work but does not: weave(p) + calico (s) 
Should work but does not: calico(p) + calico (s) 

## Current Behavior

Pod doesn't come up and calico keeps trying to get the eth0 interface on pod. Please follow the link for detailed info: https://github.com/intel/multus-cni/issues/241 

## Possible Solution

It might be the case that calico is looking for the default interface eth0 (on pod) all the time and in case it is being occupied by first CNI, calico (second interface) doesn't add up correctly.

## Steps to Reproduce (for bugs)

1.  Use multus-cni as your default CNI plugin
2. Add multiple networks using multus CRD
3. Try launching a pod with multiple network interface (second being calico). config examples are on this link: https://github.com/intel/multus-cni/issues/241

## Your Environment

* CNI plugin version (e.g. `/opt/cni/bin/calico --version`): v3.4.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubeadm version: &version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:36:44Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
* CNI config: 

> 10-calico
```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: 10-calico
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "calico",
      "log_level": "info",
      "datastore_type": "kubernetes",
      "nodename": "test",
      "mtu": 1440,
      "ipam": {
        "type": "host-local",
        "subnet": "172.22.0.0/16"
      },
      "policy": {
          "type": "k8s"
      },
      "kubernetes": {
          "kubeconfig": "/etc/cni/multus/calico/net.d/calico-kubeconfig"
      }
    }'
```
> 20-calico
```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: 20-calico
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "calico",
      "log_level": "info",
      "datastore_type": "kubernetes",
      "nodename": "test",
      "mtu": 1440,
      "ipam": {
        "type": "host-local",
        "subnet": "172.26.0.0/16"
      },
      "policy": {
          "type": "k8s"
      },
      "kubernetes": {
          "kubeconfig": "/etc/cni/multus/calico/net.d/calico-kubeconfig"
      }
    }'
```
* Operating System and version:  Ubuntu 16.04.5 LTS
* Link to your project (optional):

**Comment by caseydavenport** [comment] 2019-01-28 19:04
Related: https://github.com/projectcalico/cni-plugin/issues/429

**Comment by caseydavenport** [comment] 2019-03-31 00:26
Going to close this as a duplicate of #429, which is tracking multi-interface support.

**Closed by caseydavenport** 2019-03-31 00:26 UTC
Labels: priority/P3
