### ISSUE TITLE
Calico with LXD

### ISSUE THREAD

**Issue by quater** [projectcalico/cni-plugin#667] opened 2018-11-28 10:17 UTC
Two years ago I filled the issue https://github.com/projectcalico/felix/issues/1080 but did not get around looking into it any further.

With this issue I would like to revive this topic and hopefully get an upstream supported way in place for Calico with LXD.

I have created the https://github.com/quater/calico-for-lxc-and-lxd repository that showcases how Calico can actually work with LXC/ LXD. However this repository is based on code changes provided by Cui Zhicheng more than 18 months ago. Since then technology has moved on so that it would require yet another similar code change to get this working with the current latest technologies. **However I wonder whether this would be the correct way of moving forward?**

### **Calico with LXD (Codeline as of 29th April 2017 with additional code changes)**

The code differences can be looked up at
https://github.com/quater/cni-plugin/compare/master...quater:calico-for-lxc
https://github.com/quater/cni/compare/master...quater:calico-for-lxc

```
# Ensure to start from scratch
$ git clone https://github.com/quater/calico-for-lxc-and-lxd.git
$ vagrant destroy -f && vagrant up && vagrant ssh

# Setup test scenario
vagrant@ubuntu-xenial:~$ cd ~/shared_folder/scripts
vagrant@ubuntu-xenial:~$ ./setup_with_code_changes.sh

# Initialize LXD - Newer versions of LXD can actually be configured automatically but this version does not.
# Simply use all default settings.
vagrant@ubuntu-xenial:~$ sudo lxd init

# Create new LXD profile without any NIC
vagrant@ubuntu-xenial:~$ sudo lxc profile create calico

# Create two LXD containers
vagrant@ubuntu-xenial:~$ cd ~/shared_folder/scripts/lxd
vagrant@ubuntu-xenial:~$ ./lxd-create.sh lxd1 calico
vagrant@ubuntu-xenial:~$ ./lxd-create.sh lxd2 calico

# Attach Calico NIC to containers
vagrant@ubuntu-xenial:~$ ./lxd-attach-calico.sh lxd1 frontend
vagrant@ubuntu-xenial:~$ ./lxd-attach-calico.sh lxd2 frontend

# Get the IP address of the Calico NIC and store in variable
vagrant@ubuntu-xenial:~$ LXD1_IP=$(sudo lxc exec lxd1 -- ip addr | grep -A 3 calico | grep -Po 'inet \K[\d.]+')
vagrant@ubuntu-xenial:~$ LXD2_IP=$(sudo lxc exec lxd2 -- ip addr | grep -A 3 calico | grep -Po 'inet \K[\d.]+')

# Verify that LXC containers can ping each other
vagrant@ubuntu-xenial:~$ sudo lxc exec lxd1 -- ping -c 3 $LXD2_IP
vagrant@ubuntu-xenial:~$ sudo lxc exec lxd2 -- ping -c 3 $LXD1_IP

# Apply Calico profile to deny ICMP packages on ingress
vagrant@ubuntu-xenial:~$ cat << EOF | calicoctl apply -f -
- apiVersion: v1
  kind: profile
  metadata:
    name: frontend
    labels:
      role: frontend
  spec:
    ingress:
    - action: deny
      protocol: icmp
      source:
        selector: role == 'frontend'
EOF

# Verify that LXC containers cannot ping each other anymore. Verifing that Calico is doing its work!
vagrant@ubuntu-xenial:~$ sudo lxc exec lxd1 -- ping -W 1 -c 3 $LXD2_IP
vagrant@ubuntu-xenial:~$ sudo lxc exec lxd2 -- ping -W 1 -c 3 $LXD1_IP

# Detach Calico NICs
vagrant@ubuntu-xenial:~$ ./lxd-detach-calico.sh lxd1 frontend
vagrant@ubuntu-xenial:~$ ./lxd-detach-calico.sh lxd2 frontend

# Destroy LXC containers
vagrant@ubuntu-xenial:~$ ./lxd-delete.sh lxd1
vagrant@ubuntu-xenial:~$ ./lxd-delete.sh lxd2
```

### **Calico with LXD (current latest version without code changes)**

The https://github.com/quater/calico-for-lxd repository shows the current state, without any code changes.

```
# Ensure to start from scratch
$ git clone https://github.com/quater/calico-for-lxd-latest-versions.git
$ vagrant destroy -f && vagrant up && vagrant ssh

# Setup test scenario
vagrant@ubuntu-xenial:~$ cd ~/shared_folder/scripts
vagrant@ubuntu-xenial:~$ ./setup_with_vanilla_code.sh

# Create new LXD profile without any NI
vagrant@ubuntu-xenial:~$ lxc profile create calico
vagrant@ubuntu-xenial:~$ cat <<EOF | lxc profile edit calico
config: {}
description: "No network defined"
devices:   
  root:
    path: /
    pool: default
    type: disk
name: calico
used_by: []
EOF

# Create two LXD containers
vagrant@ubuntu-xenial:~$ ./lxd-create.sh lxd1 calico
vagrant@ubuntu-xenial:~$ ./lxd-create.sh lxd2 calico

# Attach Calico NI to lxd1
vagrant@ubuntu-xenial:~$ ./lxd-attach-calico.sh lxd1 frontend

# Observe that the lxd1 container can be reached from the vagrant machine
vagrant@ubuntu-xenial:~$ ping $(lxc ls lxd1 | egrep -o "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+")

# Try to attach the Calico NI to lxd2
vagrant@ubuntu-xenial:~$ ./lxd-attach-calico.sh lxd2 frontend

# Observe that Calico is not assigning an IP address to the second container lxd2
vagrant@ubuntu-xenial:~$ lxc ls

# Detach Calico NIs
vagrant@ubuntu-xenial:~$ ./lxd-detach-calico.sh lxd1 frontend
vagrant@ubuntu-xenial:~$ ./lxd-detach-calico.sh lxd2 frontend

# Destroy LXC containers
vagrant@ubuntu-xenial:~$ ./lxd-delete.sh lxd1
vagrant@ubuntu-xenial:~$ ./lxd-delete.sh lxd2
```

From what I can tell at the moment, to make Calico work with LXD may require the use or modification in one or some of the below repositories.

https://github.com/containernetworking/cni
https://github.com/projectcalico/libcalico-go
https://github.com/projectcalico/cni-plugin
https://github.com/lxc/lxd

**What is your opinion? What would be the ideal way of getting Calico to work with LXD?**

**Comment by quater** [comment] 2018-12-11 16:37
@fasaxc Ideally, I would like to have the ability to have multiple network interfaces managed by Calico.

In the meantime I have got Calico 3.4 working with LXC/ LXD by the use of the https://github.com/quater/cni/blob/42e857f0a2bfe4048a592c1bc634dfdfdb68c42f/cnitool/cnitool.go (currently on master only). The *cnitool* generates a unique container Id by generating a hash based on the path to the Linux network namespace. Note, this solution does not require any code changes in any of the involved projects/ repositories!

Please see https://github.com/quater/calico-for-lxd for details.

The only caveat is that it is only possible to attach one Calico managed network interface to the container, whereas ideally I would like to attach multiple network interfaces and manage them with Calico.

It fails at the point of adding the routes in the container. The error is **failed to add route inside the container: file exists**. The full output is available as a gist at https://gist.github.com/quater/e3f7931eec135500031313d36f40468d.

How can I overcome this limitation (i.e. only one Calico NI per container) with Calico 3.4?

**Comment by quater** [comment] 2019-01-11 12:07
@fasaxc As from the discussion we had on Slack, I learned that Calico's cni-plugin does not currently support multiple network interfaces since Kubernetes does not natively support this either.

However I wonder if Calico's cni-plugin could be enhanced to support multiple network interfaces attached to the same container? In my use case this would be in conjunction with LXD but there are also Kubernetes projects out there (i.e. https://github.com/Huawei-PaaS/CNI-Genie or https://github.com/intel/multus-cni) for which this capability would be equally useful and would make Calico the tool of choice for so many others!

What do you think?

**Comment by caseydavenport** [comment] 2019-03-31 00:27
Is the only thing missing here support for multiple interfaces?

If so, I think we should close as a duplicate of the main thread here: https://github.com/projectcalico/cni-plugin/issues/429

**Comment by tmjd** [comment] 2019-09-09 20:44
Duplicate: #429

**Closed by tmjd** 2019-09-09 20:44 UTC
Labels: kind/support
